/**
 * @file CrimeTypes.js
 * @description IPC / BNS Standard Indian Police Crime Types
 * @author KCIP Engineering Team
 * @version 1.0.0
 * @lastUpdated 2026-07-25
 */

export const CrimeTypes = Object.freeze({ MURDER: 'MURDER', ROBBERY: 'ROBBERY', DACOITY: 'DACOITY', BURGLARY: 'BURGLARY', THEFT: 'THEFT', ASSAULT: 'ASSAULT', CYBER_CRIME: 'CYBER_CRIME', NDPS_NARCOTICS: 'NDPS_NARCOTICS', POCSO: 'POCSO', WOMAN_HARASSMENT: 'WOMAN_HARASSMENT', RIOTING: 'RIOTING', KIDNAPPING: 'KIDNAPPING', CHEATING_FRAUD: 'CHEATING_FRAUD', MOTOR_VEHICLE_THEFT: 'MOTOR_VEHICLE_THEFT', ARSON: 'ARSON' });
