/**
 * @file InvestigationStatus.js
 * @description Granular Procedural Investigation Process Stages
 * @author KCIP Engineering Team
 * @version 1.0.0
 * @lastUpdated 2026-07-25
 */

export const InvestigationStatus = Object.freeze({ INITIAL_INQUIRY: 'INITIAL_INQUIRY', SCENE_VISITED: 'SCENE_VISITED', EVIDENCE_COLLECTED: 'EVIDENCE_COLLECTED', SUSPECT_IDENTIFIED: 'SUSPECT_IDENTIFIED', ARREST_MADE: 'ARREST_MADE', INTERROGATION_IN_PROGRESS: 'INTERROGATION_IN_PROGRESS', FORENSIC_PENDING: 'FORENSIC_PENDING', CHARGESHEET_DRAFTED: 'CHARGESHEET_DRAFTED', FINAL_REPORT_SUBMITTED: 'FINAL_REPORT_SUBMITTED' });
